/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:54cd6f7e-b7c3-42f8-8c17-85fda80b4263",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Thyn4vEUw",
    "aws_user_pools_web_client_id": "6qb7l0vt6563h35n6rsf4j2mm6",
    "oauth": {}
};


export default awsmobile;
